"""New Migration

Revision ID: 1bcfed7f0078
Revises: 
Create Date: 2022-03-10 06:49:35.405534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bcfed7f0078'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Restaurants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Restaurants_id'), 'Restaurants', ['id'], unique=True)
    op.create_table('Customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('partysize', sa.Integer(), nullable=True),
    sa.Column('restaurantId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurantId'], ['Restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phoneNumber')
    )
    op.create_index(op.f('ix_Customers_id'), 'Customers', ['id'], unique=True)
    op.create_table('Queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['Customers.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['Restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Queues_id'), 'Queues', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Queues_id'), table_name='Queues')
    op.drop_table('Queues')
    op.drop_index(op.f('ix_Customers_id'), table_name='Customers')
    op.drop_table('Customers')
    op.drop_index(op.f('ix_Restaurants_id'), table_name='Restaurants')
    op.drop_table('Restaurants')
    # ### end Alembic commands ###
