"""New Migration

Revision ID: 053db3dafcd4
Revises: 
Create Date: 2022-03-10 07:11:11.679319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053db3dafcd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Queues', sa.Column('partySize', sa.Integer(), nullable=True))
    op.add_column('Restaurants', sa.Column('queueId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Restaurants', 'Queues', ['queueId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Restaurants', type_='foreignkey')
    op.drop_column('Restaurants', 'queueId')
    op.drop_column('Queues', 'partySize')
    # ### end Alembic commands ###
