"""empty message

Revision ID: 125252d9039b
Revises: 365255054e28
Create Date: 2022-03-13 01:39:39.941825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125252d9039b'
down_revision = '365255054e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Queue_restaurant_id_fkey', 'Queue', type_='foreignkey')
    op.drop_column('Queue', 'restaurant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Queue', sa.Column('restaurant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('Queue_restaurant_id_fkey', 'Queue', 'Restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###
