"""empty message

Revision ID: 365255054e28
Revises: 
Create Date: 2022-03-12 23:39:34.441597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365255054e28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Restaurants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Restaurants_id'), 'Restaurants', ['id'], unique=True)
    op.create_table('Queue',
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('partySize', sa.Integer(), nullable=True),
    sa.Column('restaurant_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['Restaurants.id'], ),
    sa.PrimaryKeyConstraint('phone_number')
    )
    op.create_index(op.f('ix_Queue_phone_number'), 'Queue', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Queue_phone_number'), table_name='Queue')
    op.drop_table('Queue')
    op.drop_index(op.f('ix_Restaurants_id'), table_name='Restaurants')
    op.drop_table('Restaurants')
    # ### end Alembic commands ###
