"""changed types

Revision ID: 5728adfe146c
Revises: e6b2148460ad
Create Date: 2022-03-12 05:30:15.044532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5728adfe146c'
down_revision = 'e6b2148460ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Restaurants_queueId_fkey', 'Restaurants', type_='foreignkey')
    op.drop_column('Restaurants', 'queueId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Restaurants', sa.Column('queueId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Restaurants_queueId_fkey', 'Restaurants', 'Queues', ['queueId'], ['id'])
    # ### end Alembic commands ###
