"""New Migration

Revision ID: e6b2148460ad
Revises: 053db3dafcd4
Create Date: 2022-03-10 07:13:54.178189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b2148460ad'
down_revision = '053db3dafcd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
